---
title: "covid-19 analysis"
author: "Matthew Prokopenko"
date: "26 07 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Let's start
Hello there! In this EDA I will look into the Kaggle dataset on COVID-19 cases, do some learning and display three countries with the highest number of positive cases against the number of cases. 
This is a guided project from dataquest.io 


```{r}
library(tidyverse)


```
```{r}
covid_df <- read.csv("covid19.csv")

dim(covid_df)

vector_cols <- colnames(covid_df)
print(vector_cols)

head(covid_df)

glimpse(covid_df)
```
```{r}
class(vector_cols)
```
```{r}
covid_df_all_states <- covid_df %>% 
  filter(Province_State == "All States") %>%
  select(-Province_State)
glimpse(covid_df_all_states)
```
```{r}
covid_df_all_states_daily <- covid_df_all_states %>%
  select(Date, Country_Region, active, hospitalizedCurr, daily_tested, daily_positive)
glimpse(covid_df_all_states_daily)
```
```{r}
covid_df_all_states_daily_sum <- covid_df_all_states_daily %>% 
  group_by(Country_Region) %>% 
  summarise(tested = sum(daily_tested), 
            positive = sum(daily_positive),
            active = sum(active),
            hospitalized = sum(hospitalizedCurr)) %>% 
  arrange(desc(tested)) #this is equivalent to `arrange(-tested)`
```


```{r}
covid_top_10 <- head(covid_df_all_states_daily_sum,10)
```

```{r}
countries <- covid_top_10$Country_Region
tested_cases <- covid_top_10$tested
positive_cases <- covid_top_10$positive
active_cases <- covid_top_10$active
hospitalized_cases <- covid_top_10$hospitalized

```

```{r}
names(tested_cases) <- countries
names(positive_cases) <- countries
names(active_cases) <- countries
names(hospitalized_cases) <- countries
```

```{r}
positive_cases/tested_cases
positive_tested_top_3 <- c("United Kingdom" = 0.11, "United States" = 0.10, "Turkey" = 0.08)

```
```{r}
united_kingdom <- c(0.11, 1473672, 166909, 0, 0)
united_states <- c(0.10, 17282363, 1877179, 0, 0)
turkey <- c(0.08, 2031192, 163941, 2980960, 0)
```

```{r}
covid_mat <- rbind(united_kingdom, united_states, turkey) 
colnames(covid_mat) <- c("Ratio", "tested", "positive", "active", "hospitalized")
```

```{r}
covid_mat
```

```{r}
question <- "Which countries have had the highest number of positive cases against the number of tests?"

answer <- c("Positive tested cases" = positive_tested_top_3)
```

```{r}
datasets <- list(
  original = covid_df,
  all_states = covid_df_all_states,
  daily = covid_df_all_states_daily,
  sum = covid_df_all_states_daily_sum
)

matrices <- list(covid_mat)

vectors <- list(vector_cols, countries)

data_structure_list <- list("dataframe" = datasets, "matrix" = matrices, "vector" = vectors)

covid_analysis_list <- list(question, answer, data_structure_list)

covid_analysis_list[[2]]
```

